spring:
  data:
    jpa:
      repositories:
        enable: false
  
    mongodb:
      uri : mongodb+srv://huy:huyvff111@cluster0.wteenm1.mongodb.net/testmongo?retryWrites=true&w=majority
      database : EcomApi
      